version: '3.3'

services:
  ntp:
    build: .
    image: cturra/ntp:latest
    container_name: ntp
    restart: always
    ports:
      - 123:123/udp
    environment:
      - NTP_SERVERS="time1.google.com,time2.google.com,time3.google.com,time4.google.com"
      - LOG_LEVEL=0